{{- if .Values.istio.enabled  }}
{{- if .Values.istio.gateway.enabled  }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "openg2p.fullname" . }}
  labels:
    {{- include "openg2p.labels" . | nindent 4 }}
spec:
  selector:
    {{ toYaml .Values.istio.gateway.ingressController | nindent 4 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      {{- if .Values.istio.gateway.host }}
      - {{ .Values.istio.gateway.host }}
      {{- else }}
      - {{ .Values.global.hostname }}
      {{- end }}
    {{- if .Values.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
      {{- if .Values.istio.gateway.host }}
      - {{ .Values.istio.gateway.host }}
      {{- else }}
      - {{ .Values.global.hostname }}
      {{- end }}
    {{- if .Values.istio.gateway.tls.enabled }}
    tls:
      {{ toYaml (omit .Values.istio.gateway.tls "enabled") | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
