{{- if .Values.selfServiceIngress.enabled }}
{{- if eq .Values.selfServiceIngress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "openg2p.fullname" . }}-self-service
  labels:
    {{- include "openg2p.labels" . | nindent 4 }}
spec:
  hosts:
  {{- if .Values.selfServiceIngress.istio.virtualservice.host }}
  - {{ .Values.selfServiceIngress.istio.virtualservice.host }}
  {{- else }}
  - {{ .Values.global.selfServiceHostname }}
  {{- end }}
  gateways:
    - {{ .Values.selfServiceIngress.istio.virtualservice.gateway }}
  http:
  - match:
    - uri:
        exact: /my
    - uri:
        prefix: /my/
    - uri:
        exact: /web
    - uri:
        exact: /web/login
    - uri:
        exact: /web/database/selector
    redirect:
      uri: /selfservice
  - route:
    - destination:
        host: {{ include "openg2p.fullname" . }}-odoo
        port:
          number: {{ .Values.odoo.service.port }}
{{- end }}
{{- end }}
