apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "common.names.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.names.fullname" . }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: enketo
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: DOMAIN
              {{- if .Values.domain }}
              value: {{ .Values.domain }}
              {{- else }}
              value: {{ .Values.global.hostname }}
              {{- end }}
            - name: SUPPORT_EMAIL
              {{- if .Values.supportEmail }}
              value: {{ .Values.supportEmail }}
              {{- else }}
              value: {{ .Values.global.sysAdminEmail }}
              {{- end }}
            - name: HTTPS_PORT
              {{- if .Values.httpsPort }}
              value: {{ .Values.httpsPort | quote }}
              {{- else }}
              value: {{ .Values.global.httpsPort | quote }}
              {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.extraEnvVarsCM }}
            {{- range .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            {{- range .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
          ports:
          - name: container-port
            containerPort: {{ .Values.containerPort }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: enketo-secrets
            mountPath: /etc/secrets
          - name: enketo-conf
            mountPath: /srv/src/enketo_express/config/config.json.template
            subPath: config.json.template
      volumes:
        - name: enketo-secrets
          secret:
            secretName: {{ include "common.names.fullname" . }}
        - name: enketo-conf
          configMap:
            name: {{ include "common.names.fullname" . }}