apiVersion: v2
name: odk-central-pyxform
description: A Helm chart for odk-central-pyxform.
type: application
version: 0.1.0
appVersion: ""
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
   - bitnami-common
  version: 1.x.x
keywords:
  - odk
  - odk-central
  - odk-central-pyxform
