global:
  kibanaEnabled: true
master:
  replicaCount: 1
  persistence:
    size: 2Gi
data:
  replicaCount: 1
  persistence:
    size: 2Gi
coordinating:
  replicaCount: 1
ingest:
  replicaCount: 1

kibana:
  persistence:
    enabled: false