envs:
  config:
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    KAFKA_CLUSTERS_0_NAME: main
    KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-zookeeper:2181
    KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://debezium-service:8083
    KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
    KAFKA_CLUSTERS_0_KAFKACONNECT_1_ADDRESS: http://es-connect:8083
    KAFKA_CLUSTERS_0_KAFKACONNECT_1_NAME: es-connect
image:
  pullPolicy: Always